#pragma once

// place overrides here
#define RGB_DI_PIN D0
#define RGBLED_NUM 3
#define RGBLIGHT_CUSTOM_LED_INIT
#define RGBLIGHT_SLEEP
#define TAPPING_TERM 200
#define RGBLIGHT_HUE_STEP 8
#define RGBLIGHT_SAT_STEP 8
#define RGBLIGHT_VAL_STEP 8
#define BACKLIGHT_LEVELS 5
#define BACKLIGHT_PIN B7

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_TIME_TO_MAX 75
#define MOUSEKEY_MAX_SPEED 15

#define MOUSEKEY_WHEEL_DELAY 20
#define MOUSEKEY_WHEEL_INTERVAL 100
#define MOUSEKEY_WHEEL_MAX_SPEED 1
#define MOUSEKEY_WHEEL_TIME_TO_MAX 200
#define MOUSE_WHEEL_DELTA 1
#define MOUSEKEY_WHEEL_MAX 1

#undef PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
